// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CityColumns holds the columns for the "city" table.
	CityColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "type", Type: field.TypeUint32, Default: 0},
		{Name: "pid", Type: field.TypeUint32, Nullable: true},
	}
	// CityTable holds the schema information for the "city" table.
	CityTable = &schema.Table{
		Name:       "city",
		Columns:    CityColumns,
		PrimaryKey: []*schema.Column{CityColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "city_province_cities",
				Columns:    []*schema.Column{CityColumns[3]},
				RefColumns: []*schema.Column{ProvinceColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CountyColumns holds the columns for the "county" table.
	CountyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "type", Type: field.TypeUint32, Default: 0},
		{Name: "pid", Type: field.TypeUint32, Nullable: true},
	}
	// CountyTable holds the schema information for the "county" table.
	CountyTable = &schema.Table{
		Name:       "county",
		Columns:    CountyColumns,
		PrimaryKey: []*schema.Column{CountyColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "county_city_counties",
				Columns:    []*schema.Column{CountyColumns[3]},
				RefColumns: []*schema.Column{CityColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LicSnColumns holds the columns for the "lic_sn" table.
	LicSnColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "dev_uuid", Type: field.TypeString, Size: 64},
		{Name: "lic_path", Type: field.TypeString, Size: 1024},
		{Name: "state", Type: field.TypeInt, Default: 0},
		{Name: "task_id", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "create_time", Type: field.TypeInt64},
	}
	// LicSnTable holds the schema information for the "lic_sn" table.
	LicSnTable = &schema.Table{
		Name:       "lic_sn",
		Columns:    LicSnColumns,
		PrimaryKey: []*schema.Column{LicSnColumns[0]},
	}
	// ProvinceColumns holds the columns for the "province" table.
	ProvinceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "type", Type: field.TypeUint32, Default: 0},
	}
	// ProvinceTable holds the schema information for the "province" table.
	ProvinceTable = &schema.Table{
		Name:       "province",
		Columns:    ProvinceColumns,
		PrimaryKey: []*schema.Column{ProvinceColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CityTable,
		CountyTable,
		LicSnTable,
		ProvinceTable,
	}
)

func init() {
	CityTable.ForeignKeys[0].RefTable = ProvinceTable
	CityTable.Annotation = &entsql.Annotation{
		Table: "city",
	}
	CountyTable.ForeignKeys[0].RefTable = CityTable
	CountyTable.Annotation = &entsql.Annotation{
		Table: "county",
	}
	LicSnTable.Annotation = &entsql.Annotation{
		Table: "lic_sn",
	}
	ProvinceTable.Annotation = &entsql.Annotation{
		Table: "province",
	}
}
