// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LicSnColumns holds the columns for the "lic_sn" table.
	LicSnColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "dev_uuid", Type: field.TypeString, Size: 64},
		{Name: "lic_path", Type: field.TypeString, Size: 1024},
		{Name: "state", Type: field.TypeInt, Default: 0},
		{Name: "task_id", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "create_time", Type: field.TypeInt64},
	}
	// LicSnTable holds the schema information for the "lic_sn" table.
	LicSnTable = &schema.Table{
		Name:       "lic_sn",
		Columns:    LicSnColumns,
		PrimaryKey: []*schema.Column{LicSnColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LicSnTable,
	}
)

func init() {
	LicSnTable.Annotation = &entsql.Annotation{
		Table: "lic_sn",
	}
}
