// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TAppAccount struct {
	ent.Schema
}

func (TAppAccount) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("orgId").Comment("所属组织单位ID"), field.String("orgName").Comment("所属组织单位名称"), field.String("account").Comment("账号"), field.String("passwd").Comment("密码"), field.String("userName").Comment("用户名"), field.String("salt").Comment("加密盐"), field.String("token").Comment("连接token"), field.String("loginModel").Comment("登录的设备型号"), field.String("loginDevice").Comment("登录的设备序列号"), field.Bool("loginScene").Comment("登录场景"), field.Time("loginTime").Comment("登录时间"), field.Float("loginLon").Comment("登录经度"), field.Float("loginLat").Comment("登录纬度"), field.Time("deadLineTime").Comment("有效期"), field.Time("updateTime").Comment("更新时间"), field.Time("createTime").Comment("创建时间")}
}
func (TAppAccount) Edges() []ent.Edge {
	return nil
}
func (TAppAccount) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_app_account"}}
}
