// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TArchiveTask struct {
	ent.Schema
}

func (TArchiveTask) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("archiveId").Comment("归档ID"), field.String("taskId").Comment("任务ID")}
}
func (TArchiveTask) Edges() []ent.Edge {
	return nil
}
func (TArchiveTask) Annotations() []schema.Annotation {
	return nil
}
