// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TDroneStatu struct {
	ent.Schema
}

func (TDroneStatu) Fields() []ent.Field {
	return []ent.Field{field.Int("id"),
 field.String("devSN").Comment("无人机SN"),
 field.String("model").Comment("无人机型号"),
 field.Time("heartTime").Comment("心跳时间"),
 field.String("worker").Comment("执行者"),
 field.Int("workerId").Comment("执行者Id"),
 field.String("taskNo").Comment("任务编号"),
 field.Int("towerId").Comment("正在巡检的杆塔"),
 field.Float("longtitude").Comment("经度"),
 field.Float("latitude").Comment("纬度"),
 field.Float("altitude").Comment("高度"),
 field.Float("speed").Comment("速度"),
 field.Int32("aircraftHead").Comment("飞机方位角(度)"),
 field.Int32("aircraftPitch").Comment("飞机俯仰角(度)"),
 field.Int32("aircraftRolll").Comment("飞机翻滚角(度)"),
 field.Int32("aircraftBattery").Comment("电池电量"),
 field.Int32("gimbalPitch").Comment("云台俯仰角"),
 field.String("imgSign").Comment("图传信号"),
 field.String("channelInterference").Comment("信道干扰强度"),
 field.String("compass").Comment("磁盘逻辑"),
 field.String("flightMode").Comment("飞行模式"),
 field.String("rtkStatus").Comment("RTK状态"),
 field.Int32("rtkNum").Comment("RTK卫星数"),
 field.Int32("satelliteNum").Comment("卫星数量"),
 field.String("download").Comment("下载信号"),
 field.String("upload").Comment("上传信号"),
 field.Float("distance").Optional().Comment("距离"),
 field.Float("verticalSpeed").Optional().Comment("垂直速度"),
 field.Float("horizontalSpeed").Optional().Comment("水平速度"),
 field.Time("createTime").Comment("创建时间"),
 field.Time("updateTime").Comment("更新时间"),
 field.Int32("signal").Comment("信号 <40：信号质量差；40-60：信号质量普通；>60：信号质量好"),
 field.Int32("rtk").Comment("0-未知；1-FIXED；2-FLOAT；3-SINGLE；4-NONE"),
 field.Float("windSpeed").Comment("风速"),
 field.Int32("storageLeftCapacity").Comment("剩余存储 MB"),
 field.Int32("homeDistance").Comment("剩余距离")}
}
func (TDroneStatu) Edges() []ent.Edge {
	return nil
}
func (TDroneStatu) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_drone_status"}}
}
