// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TLineTowerInfo struct {
	ent.Schema
}

func (TLineTowerInfo) Fields() []ent.Field {
	return []ent.Field{field.Int("id"),
 field.Int("lineId").Comment("线路ID"),
 field.Int("towerId").Comment("塔资产ID"),
 field.String("towerNo").Comment("塔号"),
 field.String("towerType").Comment("塔类型"),
 field.Time("updateTime").Comment("更新时间"),
 field.Time("createTime").Comment("创建时间"),
 field.Int32("sort").Comment("组内排序"),
 field.Float32("span").Comment("档距，距上一级杆塔")}
}
func (TLineTowerInfo) Edges() []ent.Edge {
	return nil
}
func (TLineTowerInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_line_tower_info"}}
}
