// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TOperationInfo struct {
	ent.Schema
}

func (TOperationInfo) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("主键id"), field.String("name").Comment("名称"), field.Time("createTime").Comment("创建时间"), field.Time("updateTime").Comment("更新时间")}
}
func (TOperationInfo) Edges() []ent.Edge {
	return nil
}
func (TOperationInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_operation_info"}}
}
