// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TOrganizationInfo struct {
	ent.Schema
}

func (TOrganizationInfo) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("orgAstId").Optional().Comment("组织单位资产ID"), field.Int("preId").Comment("上级ID"), field.String("orgName").Optional().Comment("组织单位名称"), field.String("mediaBucket").Optional().Comment("文件bucket"), field.Time("createTime").Optional().Comment("创建时间"), field.Time("updateTime").Optional().Comment("更新时间"), field.String("tagPath").Optional().Comment("tagPath")}
}
func (TOrganizationInfo) Edges() []ent.Edge {
	return nil
}
func (TOrganizationInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_organization_info"}}
}
