// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TTaskTower struct {
	ent.Schema
}

func (TTaskTower) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), 
	field.Int("taskId").Comment("任务ID"),
	 field.Int("towerId").Comment("杆塔ID"), 
	 field.Int8("status").Comment("0-未巡检，1-已完成"), 
	 field.Time("createTime"), 
	 field.Time("overTime")}
}
func (TTaskTower) Edges() []ent.Edge {
	return nil
}
func (TTaskTower) Annotations() []schema.Annotation {
	return nil
}
