// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TTowerRouteDoc struct {
	ent.Schema
}

func (TTowerRouteDoc) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("towerId").Comment("杆塔ID"), field.String("droneModel").Comment("无人机机型"), field.String("fileName").Comment("文件名称"), field.String("mediaId").Comment("mediaId"), field.Int("createId").Comment("创建者ID"), field.String("createAccount").Comment("创建者账号"), field.Int8("planMethod").Comment("0：AI自适应，1：采点，2：点云规划"), field.Time("updateTime").Comment("更新时间"), field.Time("createTime").Comment("创建时间")}
}
func (TTowerRouteDoc) Edges() []ent.Edge {
	return nil
}
func (TTowerRouteDoc) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_tower_route_doc"}}
}
