// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TVideoStream struct {
	ent.Schema
}

func (TVideoStream) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("devSN").Comment("设备SN"), field.Int8("switch").Comment("开关"), field.Int32("bitRate").Comment("推流波特率"), field.Time("updateTime").Comment("更新时间"), field.Time("createTime").Comment("创建时间")}
}
func (TVideoStream) Edges() []ent.Edge {
	return nil
}
func (TVideoStream) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "t_video_stream"}}
}
