// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"expezgo/pkg/ent/licence"
	"expezgo/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LicenceDelete is the builder for deleting a Licence entity.
type LicenceDelete struct {
	config
	hooks    []Hook
	mutation *LicenceMutation
}

// Where appends a list predicates to the LicenceDelete builder.
func (ld *LicenceDelete) Where(ps ...predicate.Licence) *LicenceDelete {
	ld.mutation.Where(ps...)
	return ld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ld *LicenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ld.sqlExec, ld.mutation, ld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ld *LicenceDelete) ExecX(ctx context.Context) int {
	n, err := ld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ld *LicenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(licence.Table, sqlgraph.NewFieldSpec(licence.FieldID, field.TypeInt64))
	if ps := ld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ld.mutation.done = true
	return affected, err
}

// LicenceDeleteOne is the builder for deleting a single Licence entity.
type LicenceDeleteOne struct {
	ld *LicenceDelete
}

// Where appends a list predicates to the LicenceDelete builder.
func (ldo *LicenceDeleteOne) Where(ps ...predicate.Licence) *LicenceDeleteOne {
	ldo.ld.mutation.Where(ps...)
	return ldo
}

// Exec executes the deletion query.
func (ldo *LicenceDeleteOne) Exec(ctx context.Context) error {
	n, err := ldo.ld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{licence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ldo *LicenceDeleteOne) ExecX(ctx context.Context) {
	if err := ldo.Exec(ctx); err != nil {
		panic(err)
	}
}
