// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"expezgo/pkg/ent/predicate"
	"expezgo/pkg/ent/province"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProvinceDelete is the builder for deleting a Province entity.
type ProvinceDelete struct {
	config
	hooks    []Hook
	mutation *ProvinceMutation
}

// Where appends a list predicates to the ProvinceDelete builder.
func (pd *ProvinceDelete) Where(ps ...predicate.Province) *ProvinceDelete {
	pd.mutation.Where(ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *ProvinceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pd.sqlExec, pd.mutation, pd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *ProvinceDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *ProvinceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(province.Table, sqlgraph.NewFieldSpec(province.FieldID, field.TypeUint32))
	if ps := pd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pd.mutation.done = true
	return affected, err
}

// ProvinceDeleteOne is the builder for deleting a single Province entity.
type ProvinceDeleteOne struct {
	pd *ProvinceDelete
}

// Where appends a list predicates to the ProvinceDelete builder.
func (pdo *ProvinceDeleteOne) Where(ps ...predicate.Province) *ProvinceDeleteOne {
	pdo.pd.mutation.Where(ps...)
	return pdo
}

// Exec executes the deletion query.
func (pdo *ProvinceDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{province.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *ProvinceDeleteOne) ExecX(ctx context.Context) {
	if err := pdo.Exec(ctx); err != nil {
		panic(err)
	}
}
