// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package errorcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-200]
	_ = x[Failed-201]
	_ = x[UNK-202]
}

const _ErrorCode_name = "OKFailedUNK"

var _ErrorCode_index = [...]uint8{0, 2, 8, 11}

func (i ErrorCode) String() string {
	i -= 200
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+200), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
